"""
Django settings for PAYMENT project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

import os
from pathlib import Path

# BASE PATH
BASE_DIR = Path(__file__).resolve().parent.parent

# SECRET KEY
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-$8*okxixg0f52vjb#d*n4p#dl$s%6t=dtaoy+t8*kd$fxc65c9'
)

# Detect Render environment
RENDER = os.environ.get("RENDER")
DEBUG = not RENDER   # DEBUG=False only on Render

# ALLOWED HOSTS
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

if RENDER:
    render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
    if render_host:
        ALLOWED_HOSTS.append(render_host)
    ALLOWED_HOSTS.append(".onrender.com")


# CSRF trusted origins
if RENDER:
    render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
    if render_host:
        CSRF_TRUSTED_ORIGINS = [
            f"https://{render_host}",
            "https://*.onrender.com"
        ]
    else:
        CSRF_TRUSTED_ORIGINS = ["https://*.onrender.com"]


# Installed Apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',

    # Local Apps
    'APIS',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # IMPORTANT

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URLS
ROOT_URLCONF = 'PAYMENT.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI
WSGI_APPLICATION = 'PAYMENT.wsgi.application'


# Database (SQLite default)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Email for development
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Password Validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ------------------------------
# STATIC FILE SETTINGS (Render)
# ------------------------------

STATIC_URL = '/static/'

# Only use STATICFILES_DIRS in local development
if not RENDER:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, "static"),
    ]

# Where collectstatic stores files
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# WhiteNoise static file storage
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default Auto Field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
