"""
Django settings for PAYMENT project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

import os
from pathlib import Path

# ------------------------------
# BASE PATH
# ------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------
# SECRET KEY
# ------------------------------
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-$8*okxixg0f52vjb#d*n4p#dl$s%6t=dtaoy+t8*kd$fxc65c9"
)

# ------------------------------
# ENVIRONMENT DETECTION
# ------------------------------
RENDER = os.environ.get("RENDER")  # Render environment variable
DEBUG = not RENDER  # Default: False on Render

# ------------------------------
# DEBUG OVERRIDE (for troubleshooting 500 on Render)
# ------------------------------
DEBUG = False
ALLOWED_HOSTS = ["paynow-qqdh.onrender.com"]  # Replace with your Render service hostname
CSRF_TRUSTED_ORIGINS = ["https://paynow-qqdh.onrender.com"]

# ------------------------------
# INSTALLED APPS
# ------------------------------
INSTALLED_APPS = [
    # Default Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",

    # Local Apps
    "APIS",
]

# ------------------------------
# MIDDLEWARE
# ------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # WhiteNoise for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ------------------------------
# URLS & WSGI
# ------------------------------
ROOT_URLCONF = "PAYMENT.urls"
WSGI_APPLICATION = "PAYMENT.wsgi.application"

# ------------------------------
# TEMPLATES
# ------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Make sure this folder exists
        "APP_DIRS": True,
        "OPTIONS": {
            "debug": DEBUG,  # Enable template debugging
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ------------------------------
# DATABASE
# ------------------------------
# Using SQLite for dev; for production, consider PostgreSQL on Render
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# ------------------------------
# EMAIL BACKEND (development)
# ------------------------------
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# ------------------------------
# PASSWORD VALIDATORS
# ------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------------
# INTERNATIONALIZATION
# ------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ------------------------------
# STATIC FILE SETTINGS
# ------------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # collectstatic destination

# Only use STATICFILES_DIRS in local development
STATICFILES_DIRS = [BASE_DIR / "static"]

# WhiteNoise storage for compressed static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ------------------------------
# DEFAULT AUTO FIELD
# ------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
