# Generated by Django 5.2.4 on 2025-07-27 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('registered_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('bank_account_num', models.CharField(max_length=30, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=20)),
                ('bank_location', models.CharField(max_length=100)),
                ('aadhaar', models.CharField(max_length=20, unique=True)),
                ('pan', models.CharField(max_length=20, unique=True)),
                ('upi_credential', models.CharField(max_length=20, unique=True)),
                ('bank_id', models.CharField(max_length=100)),
                ('balance', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
