# Generated by Django 5.2.4 on 2025-07-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
