# Generated by Django 5.2.4 on 2025-07-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0002_userprofile_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(unique=True),
        ),
    ]
