# Generated by Django 5.2.4 on 2025-08-06 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0004_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver_bank_account',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='receiver_bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='receiver_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_bank_account',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
