# Generated by Django 5.2.4 on 2025-08-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0005_transactions_receiver_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver_phone_number',
            field=models.CharField(null=True),
        ),
    ]
