# Generated by Django 5.2.4 on 2025-08-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0006_transactions_receiver_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='sender_phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
