# Generated by Django 5.2.4 on 2025-08-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0007_transactions_sender_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
