# Generated by Django 5.2.4 on 2025-08-07 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0008_delete_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20, null=True, unique=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sender_name', models.CharField(max_length=100, null=True)),
                ('sender_phone_number', models.CharField(max_length=50, null=True)),
                ('sender_bank_name', models.CharField(max_length=100, null=True)),
                ('sender_bank_account', models.CharField(blank=True, max_length=30, null=True)),
                ('sender_bank_id', models.CharField(max_length=100, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('receiver_bank_ID', models.CharField(max_length=100, null=True)),
                ('receiver_name', models.CharField(max_length=100, null=True)),
                ('receiver_phone_number', models.CharField(null=True)),
                ('receiver_bank_account', models.CharField(max_length=30, null=True)),
                ('receiver_bank_name', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
