# Generated by Django 5.2.4 on 2025-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0009_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
