# Generated by Django 5.2.4 on 2025-08-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0010_transactions_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='favourate',
            field=models.BooleanField(null=True),
        ),
    ]
