# Generated by Django 5.2.4 on 2025-08-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0011_transactions_favourate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='favourate',
        ),
    ]
