# Generated by Django 5.2.4 on 2025-08-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0012_remove_transactions_favourate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='receiver_upi_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sender_upi_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
