# Generated by Django 5.2.4 on 2025-08-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0013_transactions_receiver_upi_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankuser',
            name='upi_credential',
        ),
    ]
