# Generated by Django 5.2.4 on 2025-08-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0014_remove_bankuser_upi_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='upi_id',
            field=models.CharField(null=True),
        ),
    ]
