# Generated by Django 5.2.4 on 2025-08-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0015_bankuser_upi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankuser',
            name='upi_id',
        ),
    ]
