# Generated by Django 5.2.4 on 2025-08-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIS', '0016_remove_bankuser_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_login_reward_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
